### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by subhani92**
would love to contribute more. I know some C++.

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hello @subhani92!
Thank you for the contribution! I found your examples very interesting.

**circle-Zdepth-30.sif**

I've got a problem with "circle-Zdepth-30.sif" file. When I tried to open it in Synfig 1.0.2 (which is our default version for testing) it gave me an warning: "Installed layer version is smaller than layer version in file".
It looks like you created this example in a newer version. Can I ask you to re-create it in 1.0.2?

I like the idea of testing Z-depth in combination with other layer.  What I would like to suggest is to use "Blur" layer instead of "Motion Blur" layer - since it's more simple and results of its work can be observed easily even with static objects.

Also, I suggest to use Z-depth value "-30" instead of "30". This way the circle will be artificiallyplaced above of Blur layer and gets out of its influence. So, if Z-depth will fail to work, then it could be easily observed.

Finally, one more suggestion is to move this test from '/sources/layers/circle' to "/sources/general" (a new category). I think this is more general test for Z-depth functionality, which is implemented globally for all (well, almost al) Synfig layers.

**rectangle-inverted-0.sif**

When I opened **rectangle-inverted-0.sif** I've got this image:

screenshot_001

Can you please elaborate about your idea for this test?

**Comment by subhani92** [comment]
for now i have modified and updated  some examples by creating them in older version(i.e. 1.0.2).
in ractangle-inverted-0.sif, It was mistakenly created with two layers (circle and rectangle both), sorry about that.
Thank you!

**Comment by morevnaproject** [comment]
> in ractangle-inverted-0.sif, It was mistakenly created with two layers (circle and rectangle both), sorry about that.

I tested the modified version of "rectangle-inverted-0.sif" and  I can see now it is pretty much the same as  "rectangle-inverted.sif". Should we remove one then?

Also, can you please make modifications to "circle-Zdepth-30.sif" as described in https://github.com/synfig/synfig-tests-regressions/pull/5#issuecomment-427587985?

Thank you! ^__^

**Comment by subhani92** [comment]
> "rectangle-inverted-0.sif". Should we remove one then?

removed.
> can you please make modifications to "circle-Zdepth-30.sif" as described in #5 (comment)?

 added.

Many thanks! for taking out time to review this.

**Comment by morevnaproject** [comment]
Looks good now! Merged.

About C++ contributions: here is a list of some simple issues good to start with - https://github.com/synfig/synfig/labels/good%20first%20issue
Please let me know if any of them are interesting for you.

Thank you!

**Comment by subhani92** [comment]
Thank you for taking out time.
I want to work on this issue-
 https://github.com/synfig/synfig/issues/635

Thank you!

**Comment by morevnaproject** [comment]
Great! Please check our build instructions to get started - https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html ^__^

**Pull request merged**
