### PR TITLE
Update for result generation

### PR DESCRIPTION
**Pull request by reSHARMA**
I tried both idiff and magick compare, they both ended up saying that the images in the reference are invalid. We can look into that later.
I'm focusing on making it work end-to-end.

### CODE REVIEW

**Comment by morevnaproject** [comment]
Looks good so far! Should I merge this now? ^__^

**Comment by reSHARMA** [comment]
Thanks, I'll just take another day :) will update you.

**Comment by reSHARMA** [comment]
@morevnaproject we are good to go :) but please feel free to tweak compare metric and threshold.

https://travis-ci.com/reSHARMA/synfig/jobs/153751488

This is also good to go: https://github.com/synfig/synfig/pull/660/

**Comment by morevnaproject** [comment]
Awesome! ^__^ And it looks like it already found some difference in rendering behavior!

**Comment by reSHARMA** [comment]
@morevnaproject is anything left other than adding more tests?

**Comment by morevnaproject** [comment]
Just wrote about that here - https://github.com/synfig/synfig/issues/634#issuecomment-433309796 ^__^

**Comment by reSHARMA** [comment]
Thanks :)

**Pull request merged**
