### PR TITLE
Add script to generate reference

### PR DESCRIPTION
**Pull request by reSHARMA**
This is a crude script for the purpose.

- I saw renderer was using multiple cores, so shall we just run sequentially and renderer will handle the threads?
- I could not get pre-build binaries work on my system, I got " error while loading shared libraries: libMagick++-6.Q16.so.6: cannot open shared object file: No such file or directory", hopefully it is just my system, do you agree?
- I got multiple files like circle0000.png circle0001.png etc, I think we don't want this?

There are some work still left, like flags for renderer.

Thanks for your patience :)

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hello! Great to see first steps!

> I saw renderer was using multiple cores, so shall we just run sequentially and renderer will handle the threads?

Well, there is an option to specify threads. But, if I remember correctly in many versions (including 1.0.2) it just doesn't works. Anyway, I think it is OK to run all tasks sequentially.

> I could not get pre-build binaries work on my system, I got " error while loading shared libraries: libMagick++-6.Q16.so.6: cannot open shared object file: No such file or directory", hopefully it is just my system, do you agree?

That's weird. I have tested on Ubuntu 16.04 and it worked fine for me. What is yours Linux version?

> I got multiple files like circle0000.png circle0001.png etc, I think we don't want this?

Yeah. Please use ```--time 0``` option.

**Comment by morevnaproject** [comment]
> I could not get pre-build binaries work on my system, I got " error while loading shared libraries: libMagick++-6.Q16.so.6: cannot open shared object file: No such file or directory", hopefully it is just my system, do you agree?

Ah, looks like I found why this happens!
Please check line47 in your script:
```/tmp/synfig-$VERSION/bin/synfig``` should be replaces with ```/tmp/synfig-$VERSION/synfig```. ^__^

**Comment by reSHARMA** [comment]
> Please check line47 in your script:
/tmp/synfig-$VERSION/bin/synfig should be replaces with /tmp/synfig-$VERSION/synfig. ^__^

My bad, thanks for taking out time to figure this out. I totally missed that :)

I'm thinking about something that will watch the source dir and will run this script automatically when the changes are detected. What do you think? :)

**Comment by morevnaproject** [comment]
> I'm thinking about something that will watch the source dir and will run this script automatically when the changes are detected. What do you think? :)

This looks like a special Travis job for this repository. =D

Travis job can run the rendering script and commit changes to this repo. I have similar procedure of "commit created by Travis" in this repository - https://github.com/morevnaproject/subtitles-translation
See https://github.com/morevnaproject/subtitles-translation/blob/master/.travis.yml and https://github.com/morevnaproject/subtitles-translation/blob/master/tool/deploy-srt.sh

**Comment by reSHARMA** [comment]
> This looks like a special Travis job for this repository. =D

I'm in midway of getting that done :)
This script will compliment it and will override all rendered png.

**Comment by morevnaproject** [comment]
Great! So, is this one is ready for merge?

**Comment by reSHARMA** [comment]
Looks good to me :)

**Comment by morevnaproject** [comment]
Done! ^__^

**Pull request merged**
