### PR TITLE
Add test for polygon layer

### PR DESCRIPTION
**Pull request by SharmaRithik**
I know some c++ and would love to contribute.

### CODE REVIEW

**Comment by morevnaproject** [comment]
Merged now. Thank you!

**Comment by morevnaproject** [comment]
@SharmaRithik 

> I know some c++ and would love to contribute.

Great! Will you be interested to take a look on this? ^__^ - https://github.com/synfig/synfig/issues/637

**Comment by SharmaRithik** [comment]
> Great! Will you be interested to take a look on this? ^__^ - [synfig/synfig#637](https://github.com/synfig/synfig/issues/637)

Many thanks,I'll come up with a pull request soon.

**Comment by morevnaproject** [comment]
Great! You might want to look for build instructions here - https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html
Please let me know if you need any additional assistance. ^__^

**Pull request closed without merging**
