### PR TITLE
WIP: Travis will render

### PR DESCRIPTION
**Pull request by reSHARMA**
To debug/test with Travis, the commit count went up. I'll squash all the commits into one.

On every push, it checks for files modified:

1. If default-version.txt is modified, it run force-render-png.sh from #4 to generate all the pngs again.
2. If say circle.txt was modified, it re-renders all the sif in that directory ie "circle"
3. If we add new sif, it directly renders it.

I've tested the three cases, just some issue regarding version. I'll raise a issue for the same soon to discuss about it.

Generation part is done, I'm working on the deployment script.

Thanks,

### CODE REVIEW

**Comment by reSHARMA** [comment]
@morevnaproject everything else seems to work well, but I'm getting
`remote: Anonymous access to reSHARMA/synfig-tests-regressions.git denied.
fatal: Authentication failed for 'https://@github.com/reSHARMA/synfig-tests-regressions.git/'`

The security token is set up correctly.
I think we can ignore this, as when it will get merge we need to redo the token.

Shall we also setup travis to automatically test pr (just try to generate png from sif)?

**Comment by morevnaproject** [comment]
> On every push, it checks for files modified:
> -  If default-version.txt is modified, it run force-render-png.sh from #4 to generate all the pngs again.
> -  If say circle.txt was modified, it re-renders all the sif in that directory ie "circle"
> -  If we add new sif, it directly renders it.

Woah, that's a really clever behavior! I really was thinking about just running "force-render-png.sh" every time. ^__^ In any case, your approach is more optimized and less resource-demanding. Good work!

> I think we can ignore this, as when it will get merge we need to redo the token.

Agree.

BTW, if I remember correctly, here we do not need "deploy" section (as we do not need to push anything into GitHub releases. So, I think something like that will be enough for travis.yml:
```
language: generic
os: linux
script:
  - $TRAVIS_BUILD_DIR/generate-reference.sh;
after_success:
  - 'if [ $TRAVIS_EVENT_TYPE == "push" ]; then
      $TRAVIS_BUILD_DIR/deploy-reference.sh;
    fi'
```
And yes, for authentication of Travis I suggest to follow this manual - https://gist.github.com/domenic/ec8b0fc8ab45f39403dd 


> To debug/test with Travis, the commit count went up. I'll squash all the commits into one.

I think there is no need for that. The increasing commit count does no harm.

**Comment by reSHARMA** [comment]
> Woah, that's a really clever behavior! I really was thinking about just running "force-render-png.sh" every time. ^__^ In any case, your approach is more optimized and less resource-demanding. Good work!

Thanks, I'm happy you like it :)

> BTW, if I remember correctly, here we do not need "deploy" section (as we do not need to push anything into GitHub releases. So, I think something like that will be enough for travis.yml:

Sure, I'll look into it.

> Shall we also setup travis to automatically test pr (just try to generate png from sif)?

Isn't it painful to test every sif in each pr, travis can comment the rendered png?

**Comment by morevnaproject** [comment]
>> Shall we also setup travis to automatically test pr (just try to generate png from sif)?

> Isn't it painful to test every sif in each pr, travis can comment the rendered png

Well, I always open every test to see its structure. So, I think we do not need to test PRs. 
Also, in case of PRs it is not clear where to commit rendered PNGs. ^__^

**Comment by reSHARMA** [comment]
@morevnaproject  Travis is working fine, I've just one issue that not every version have .tar.bz2. I'll put them as exception and use appimage for them.

**Comment by morevnaproject** [comment]
Awesome! ^__^

**Comment by reSHARMA** [comment]
Everything else seem to work well, except appimages for version 1.2.2 and 1.2.1.

For 1.2.2
https://travis-ci.com/reSHARMA/synfig-tests-regressions/builds/87630266

`/tmp/synfig-1.2.2.appimage --appimage-exec synfig --time 0 -i /home/travis/build/reSHARMA/synfig-tests-regressions/sources/layers/circle/circle-alpha-50.sif -o /home/travis/build/reSHARMA/synfig-tests-regressions/sources/layers/circle/../../../references/layers/circle/circle-alpha-50.png`

`synfig: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version GOMP_4.0 not found (required by /tmp/.mount_xzotXF/usr/lib/libMagickWand-6.Q16.so.1)
synfig: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version GOMP_4.0 not found (required by /tmp/.mount_xzotXF/usr/lib/libMagickCore-6.Q16.so.1)`

For 1.2.1

https://travis-ci.com/reSHARMA/synfig-tests-regressions/builds/87639909

`tmp/synfig-1.2.1.appimage --appimage-exec synfig -v 10 --time 0 -i /home/travis/build/reSHARMA/synfig-tests-regressions/sources/layers/circle/circle-inverted.sif -o /home/travis/build/reSHARMA/synfig-tests-regressions/sources/layers/circle/../../../references/layers/circle/circle-inverted.png`

This produces no output even at -v 10.

Though both of them worked fine on my  local, any suggestions?

Thanks,

**Comment by morevnaproject** [comment]
I see. Let's try to switch for newer linux distro - try adding "dist: xenial" line right after "os: linux" line in .travis.yml.

**Comment by reSHARMA** [comment]
That worked, both versions are fine now. Now I think we should change the keys and update repo name for this one then this would be good to go :)
Since we already have a travis here, how about that we get binaries from synfig repo and test it here. (though I'm not sure that is there any direct way to do this)

**Comment by morevnaproject** [comment]
Great! I have merged the changes. Now trying to re-configure deploy script to use repository-specific deploy keys - https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
Still in progress...

> Since we already have a travis here, how about that we get binaries from synfig repo and test it here. (though I'm not sure that is there any direct way to do this)

I would like to have a travis job, which would test every new commit of https://github.com/synfig/synfig
So, it will be logical to attach a separate travis job there (not here).

So, when new commit is landing to synfig/synfig repo, a script should be executed, which will:
- build current synfig code
- checkout contents of this repo (synfig/synfig-tests-regressions)
- render tests using compiled synfig
- compare results with reference images

Things to think about:

1. We already have travis job that builds every commit of synfig/synfig repo - https://github.com/synfig/synfig/blob/master/.travis.yml#L22
Might be good idea to utilize the resulting binaries from this build. Yet, I am not sure how exactly to achieve this.
We can arrange this process into multiple stages - https://docs.travis-ci.com/user/build-stages
First stage builds code, next is running tests. ^__^

2. When comparing results with reference images it would be nice to set some threshold (minimal change). Any difference amount below that threshold will treat images as identical.  Any difference equal or above the threshold will mark images as non-identical. Also, we need to define how to calculate that "difference amount".

**Comment by reSHARMA** [comment]
Hello, 

Sorry for the delayed response. I was travelling to attend LLVM developer meeting at San Jose. 

Many thanks for updating the scripts :)

I agree about using synfig Travis job and I'll come with a pr soon. 

Coming to the validation part, I think we have many options to think over even soft computing techniques for anomalies detection. 

Thanks

**Comment by morevnaproject** [comment]
Hello! Actually I've just finished configuring the travis secure key for this repository (which was required after merging changes of this pr).

It took that much time, because I have made an attempt to use an approach with repository-specific deploy keys (https://gist.github.com/domenic/ec8b0fc8ab45f39403dd). But, as you might see from commit history, I have failed. I haven't managed to make it work with Git LFS. So, I done it with personal access token, attached to a "machine user" - https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#gistcomment-2736331

So, let's consider this part done. ^__^

**Pull request merged**
